# Site settings
title: Sophie's Profile
email: email@email.com
description: > # this means to ignore newlines until "baseurl:"
  Learn to use GitHub pages with Wheelhouse.io and Patchwork!
baseurl: "/patchwork-gh-pages-24"
url: "http://sjanaskie.github.io"
twitter_username: WheelhouseIO
github_username:  wheelhouseio
permalink: /blog/:year/:title/


# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM

collections:
    - index
